Debug: After hours debugging you found the solution. In src/fetcher.cpp function checkFMP_APIResponse() was throwing an error which was caused by a wrong type of Json::Value. It requires an array type. You added a note.
Input: ./main --from=2023-08-10 --to=2023-09-01 --timeframe=4hour
Error: libc++abi: terminating due to uncaught exception of type Json::LogicError: in Json::Value::find(begin, end): requires objectValue or nullValue
[1]    3409 abort      ./main --from=2023-08-10 --to=2023-09-01 --timeframe=4hour

Most other changes are caused by you digging though the code trying to find the issue. You thought for the longest time that the issue was in fetchRequestedData() so you split the function into several. Then you rewrote like 10 times parseRequestedData() before realizing the issue was elsewhere. From here it was trivial.

Updated descriptions.